#!/sbin/sh
#USB MASS STORAGE MODE (UMS)
#ENABLE/DISABLE UMS MODE for external sdcard :
#Off (Default)

#AOSP 4.4.4

USB_GADGET="/sys/devices/platform/omap/musb-omap2430/musb-hdrc/gadget/lun0/file"

/sbin/busybox echo "" > $USB_GADGET
/sbin/busybox sleep 2
/system/bin/vold
/sbin/busybox sleep 2

/sbin/busybox echo 0 > /sys/class/android_usb/android0/enable
/system/bin/setprop persist.sys.usb.config mtp,adb
/sbin/busybox echo 04e8 > write /sys/class/android_usb/android0/idVendor
/sbin/busybox echo 6860 > write /sys/class/android_usb/android0/idProduct
/sbin/busybox echo "mtp,adb" > /sys/class/android_usb/android0/functions
/sbin/busybox echo 1 > /sys/class/android_usb/android0/enable
/system/bin/setprop sys.usb.state mtp,adb

