#!/sbin/sh
#AGNi Main Profiles Selection
#This affects only CPU governor, CPU Max Frequency, GPU Frequency, LMK minfree
#Gaming

/sbin/busybox mount -o rw,remount /
/sbin/busybox sh /sbin/sysrw

# Clearing existing selected relevant scripts
/sbin/busybox rm /system/etc/init.d/S47enable_001bkgov*
/sbin/busybox rm /system/etc/init.d/S50enable_001bkcpufreq*
/sbin/busybox rm /system/etc/init.d/S53enable_001bkgpufreq*
/sbin/busybox rm /system/etc/init.d/*001bkschedmcpowersavings*
/sbin/busybox rm /system/etc/init.d/*001bklmkminfree*

# Moving relevant scripts
/sbin/busybox cp /res/scripts/S50enable_001bkcpufreq_040-1200 /system/etc/init.d
/sbin/busybox cp /res/scripts/S53enable_001bkgpufreq_005-384 /system/etc/init.d
/sbin/busybox cp /res/scripts/S59enable_001bklmkminfree_050-aggressive /system/etc/init.d

/sbin/busybox chmod 0775 /res/scripts/S47enable_001bkgov_001-interactive_default
/sbin/busybox chmod 0775 /system/etc/init.d/S50enable_001bkcpufreq_040-1200
/sbin/busybox chmod 0775 /system/etc/init.d/S53enable_001bkgpufreq_005-384
/sbin/busybox chmod 0775 /res/scripts/S77enable_001bkschedmcpowersavings_010-off_default
/sbin/busybox chmod 0777 /system/etc/init.dS59enable_001bklmkminfree_050-aggressive

# Executing Scripts

/sbin/busybox sh /res/scripts/S47enable_001bkgov_001-interactive_default
/sbin/busybox sh /system/etc/init.d/S50enable_001bkcpufreq_040-1200
/sbin/busybox sh /system/etc/init.d/S53enable_001bkgpufreq_005-384
/sbin/busybox sh /res/scripts/S77enable_001bkschedmcpowersavings_010-off_default
/sbin/busybox sh /system/etc/init.d/S59enable_001bklmkminfree_050-aggressive

## Setting this script as non-executable
/sbin/busybox chmod 0644 /system/etc/init.d/S46enable_001bkprofiles_*

# Mounting / & /system RO
/sbin/busybox mount -o ro,remount /
/sbin/busybox sh /sbin/sysro

