#!/sbin/sh
#AGNi Main Profiles Selection
#This affects only CPU governor, CPU Max Frequency, GPU Frequency, LMK minfree
#Extreme Battery Save

/sbin/busybox mount -o rw,remount /
/sbin/busybox sh /sbin/sysrw

# Clearing existing selected relevant scripts
/sbin/busybox rm /system/etc/init.d/S47enable_001bkgov*
/sbin/busybox rm /system/etc/init.d/S50enable_001bkcpufreq*
/sbin/busybox rm /system/etc/init.d/S53enable_001bkgpufreq*
/sbin/busybox rm /system/etc/init.d/*001bkschedmcpowersavings*
/sbin/busybox rm /system/etc/init.d/*001bklmkminfree*

# Moving relevant scripts
/sbin/busybox cp /res/scripts/S47enable_001bkgov_060-zzmoove_battsave /system/etc/init.d
/sbin/busybox cp /res/scripts/S50enable_001bkcpufreq_060-800 /system/etc/init.d
/sbin/busybox cp /res/scripts/S77enable_001bkschedmcpowersavings_030-max /system/etc/init.d
/sbin/busybox cp /res/scripts/S59enable_001bklmkminfree_040-medium /system/etc/init.d

/sbin/busybox chmod 0775 /system/etc/init.d/S47enable_001bkgov_060-zzmoove_battsave
/sbin/busybox chmod 0775 /system/etc/init.d/S50enable_001bkcpufreq_060-800
/sbin/busybox chmod 0775 /res/scripts/S53enable_001bkgpufreq_001-307_default
/sbin/busybox chmod 0775 /system/etc/init.d/S77enable_001bkschedmcpowersavings_030-max
/sbin/busybox chmod 0777 /system/etc/init.d/S59enable_001bklmkminfree_040-medium

# Executing Scripts

/sbin/busybox sh /system/etc/init.d/S47enable_001bkgov_060-zzmoove_battsave
/sbin/busybox sh /system/etc/init.d/S50enable_001bkcpufreq_060-800
/sbin/busybox sh /res/scripts/S53enable_001bkgpufreq_001-307_default
/sbin/busybox sh /system/etc/init.d/S77enable_001bkschedmcpowersavings_030-max
/sbin/busybox sh /system/etc/init.d/S59enable_001bklmkminfree_040-medium

## Setting this script as non-executable
/sbin/busybox chmod 0644 /system/etc/init.d/S46enable_001bkprofiles_*

# Mounting / & /system RO
/sbin/busybox mount -o ro,remount /
/sbin/busybox sh /sbin/sysro

