#!/sbin/sh
#AGNi preloadSWAP 512MB
#Enable or disable preloadSWAP with 2nd priority:
#Off (default)

PRELOAD="/dev/block/platform/omap/omap_hsmmc.1/by-name/HIDDEN"

umount /preload
mount -o rw,remount /
mkdir /preload
mount -o ro,remount /
swapoff $PRELOAD && /sbin/busybox mke2fs $PRELOAD && /sbin/make_ext4fs $PRELOAD && mount -t ext4 -o nosuid,nodev,noatime,nodiratime,discard $PRELOAD /preload;
