#!/sbin/sh
#USB MASS STORAGE MODE (UMS)
#ENABLE/DISABLE UMS MODE for external sdcard :
#On

#AOSP 4.4.4

USB_GADGET="/sys/devices/platform/omap/musb-omap2430/musb-hdrc/gadget/lun0/file"

EXTERNAL_SD_MOUNT_POINT="`mount | grep vold | cut -f 2 -d ' '`"
EXTERNAL_SD_LOCATION="`mount | grep vold | cut -f 1 -d ' '`"

/sbin/busybox sync
/sbin/busybox umount -l $EXTERNAL_SD_MOUNT_POINT
/system/bin/setprop persist.sys.usb.config mass_storage,adb
/sbin/busybox echo "$EXTERNAL_SD_LOCATION" > $USB_GADGET

/sbin/busybox echo 0 > /sys/class/android_usb/android0/enable
/sbin/busybox echo 04e8 > write /sys/class/android_usb/android0/idVendor
/sbin/busybox echo 685e > write /sys/class/android_usb/android0/idProduct
/sbin/busybox echo "mass_storage,adb" > /sys/class/android_usb/android0/functions
/sbin/busybox echo 1 > /sys/class/android_usb/android0/enable
/system/bin/setprop sys.usb.state mass_storage,adb

