#!/sbin/sh
#AGNi Main Profiles Selection
#This affects only CPU governor, CPU Max Frequency, GPU Frequency, LMK minfree
#Normal (default)

/sbin/busybox mount -o rw,remount /
/sbin/busybox sh /sbin/sysrw

# Clearing existing selected relevant scripts
/sbin/busybox rm /system/etc/init.d/S47enable_001bkgov*
/sbin/busybox rm /system/etc/init.d/S50enable_001bkcpufreq*
/sbin/busybox rm /system/etc/init.d/S53enable_001bkgpufreq*
/sbin/busybox rm /system/etc/init.d/*001bkschedmcpowersavings*
/sbin/busybox rm /system/etc/init.d/*001bklmkminfree*

/sbin/busybox chmod 0775 /res/scripts/S47enable_001bkgov_001-interactive_default
/sbin/busybox chmod 0775 /res/scripts/S50enable_001bkcpufreq_050-1008_default
/sbin/busybox chmod 0775 /res/scripts/S53enable_001bkgpufreq_001-307_default
/sbin/busybox chmod 0775 /res/scripts/S77enable_001bkschedmcpowersavings_010-off_default
/sbin/busybox chmod 0777 /res/scripts/S59enable_001bklmkminfree_010-normal_default

# Moving relevant scripts


# Executing Scripts

/sbin/busybox sh /res/scripts/S47enable_001bkgov_001-interactive_default
/sbin/busybox sh /res/scripts/S50enable_001bkcpufreq_050-1008_default
/sbin/busybox sh /res/scripts/S53enable_001bkgpufreq_001-307_default
/sbin/busybox sh /res/scripts/S77enable_001bkschedmcpowersavings_010-off_default
/sbin/busybox sh /res/scripts/S59enable_001bklmkminfree_010-normal_default

## Setting this script as non-executable
/sbin/busybox chmod 0644 /system/etc/init.d/S46enable_001bkprofiles_*

# Mounting /system RO
/sbin/busybox mount -o ro,remount /
/sbin/busybox sh /sbin/sysro

