#!/system/bin/sh
#CPU Governor
#Change CPU governor:
#Interactive (default)

# switch governor
echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

/sbin/busybox sleep 2

echo "100000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/boost
echo "50" > /sys/devices/system/cpu/cpufreq/interactive/go_highspeed_load
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/input_boost
echo "60000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "0" > /sys/devices/system/cpu/cpufreq/interactive/screen_off_differential
echo "20000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate


