#!/system/bin/sh
#Governor
#Change CPU governor:
#Hotplug

# switch governor
echo "hotplug" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

/sbin/busybox sleep 2

echo "10" > /sys/devices/system/cpu/cpufreq/hotplug/down_differential
echo "35" > /sys/devices/system/cpu/cpufreq/hotplug/down_threshold
echo "5" > /sys/devices/system/cpu/cpufreq/hotplug/hotplug_in_sampling_periods
echo "10" > /sys/devices/system/cpu/cpufreq/hotplug/hotplug_out_sampling_periods # 20
echo "0" > /sys/devices/system/cpu/cpufreq/hotplug/ignore_nice_load
echo "0" > /sys/devices/system/cpu/cpufreq/hotplug/io_is_busy
echo "500000" > /sys/devices/system/cpu/cpufreq/hotplug/sampling_rate # 100000
echo "60" > /sys/devices/system/cpu/cpufreq/hotplug/up_threshold # 80

