#!/system/bin/sh
#CPU Max Frequency
#Change CPU maximum scaling:
#1.35 GHz

chmod 0664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 1350000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 0444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
